# Home and Work Assign RID

This code is used to re-assign the roadID for each workplace. The distance function in geopandas fialed to generate the correct distance, so I create a new distance function in this code

In [1]:
import geopandas as gpd
import pandas as pd
import numpy as np
import timeit
import multiprocessing
from math import sin, cos, sqrt, atan2, radians

### Load Data

In [2]:
#Home CT
homect = gpd.read_file('../Shp_Study_Area_Richard/Home_Point/Home_By_State/home_ct.shp')
print("CT size", len(homect))
#Home NJ
#Home PA
#homepa = gpd.read_file('../Shp_Study_Area_Richard/Home_Point/Home_By_State/home_pa.shp')
#print("PA size", len(homepa))

CT size 1326196

In [3]:
homect.head()

              hhold       long        lat                    geometry
0     09001010101h0 -73.698597  41.112328  POINT (-73.69860 41.11233)
1     09001010101h1 -73.670429  41.097875  POINT (-73.67043 41.09788)
2    09001010101h10 -73.667156  41.046854  POINT (-73.66716 41.04685)
3   09001010101h100 -73.720042  41.099381  POINT (-73.72004 41.09938)
4  09001010101h1000 -73.684385  41.056047  POINT (-73.68439 41.05605)

In [4]:
#Road
road = gpd.read_file('../Shp_Study_Area_Richard/Road_Point/road_points_Aug_Richard.shp')
road.shape

(1250082, 5)

In [7]:
road['RID'] = road['RDID']

In [8]:
road.head()

   RDID STATE       Long        Lat                    geometry  RID
0     1    34 -74.658902  40.157278  POINT (-74.65890 40.15728)    1
1     2    09 -73.227316  41.225055  POINT (-73.22732 41.22506)    2
2     3    09 -73.225156  41.225181  POINT (-73.22516 41.22518)    3
3     4    09 -73.221523  41.232643  POINT (-73.22152 41.23264)    4
4     5    09 -73.210993  41.235990  POINT (-73.21099 41.23599)    5

## Functions

In [9]:
def new_distance(x1, y1, x2, y2):
    # approximate radius of earth in km
    R = 6373.0
    
    lat1 = radians (x1)
    long1 = radians (y1)
    lat2 = radians(x2)
    long2 = radians(y2)
    
    dlon = long2 - long1
    dlat = lat2 - lat1
    
    a = sin(dlat / 2)**2 + cos(lat1) * cos(lat2) * sin(dlon / 2)**2
    c = 2 * atan2(sqrt(a), sqrt(1 - a))

    distance = R * c
    return distance

In [10]:
def assign_rid(data, road):
    #Geo Location
    d_geometry = data.geometry
    #print(d_geometry)
    
    #Create Buffer for each Home or Work Point
    buff = data.geometry.buffer(0.001)
    # Lat and Long
    x = data.lat
    y = data.long
    #print("Site Lat",x)
    #print("Site Long", y)
    
    #Find Intersected points
    r_in = road[road.intersects(buff)].copy()
    #print("Intersected road points numbers:", len(r_in))

    if r_in.empty:
        #print(data.wrkID, "First Empty")
        buff = data.geometry.buffer(0.02)
        r_in = road[road.intersects(buff)].copy()
        #Intersect Road Point Lat list
        rx = r_in.loc[:,'Lat'].tolist()
        #Intersect Road Point Long list
        ry = r_in.loc[:, 'Long'].tolist()
        
        #Calculate Distance between the point and intersected road points 
        dist = []
        for j in range(0, len(r_in)):
            d = new_distance(x, y, rx[j], ry[j])
            dist.append(d)  
        #print("Distance list's length",len(dist))
            
        rid = r_in.loc[:,'RDID']
        #Create DF
        df_rd = pd.DataFrame({'RDID': rid, 'Dist':dist}).sort_values(by='Dist')
        #print(df_rd.head(1))
        #print(df_rd.iloc[0, 0])
        #r_id.append(df_rd.iloc[0, 0])
        return df_rd.iloc[0, 0]
    
    else:
        #Intersect Road Point Lat list
        rx = r_in.loc[:,'Lat'].tolist()
        #Intersect Road Point Long list
        ry = r_in.loc[:, 'Long'].tolist()
        
        #Calculate Distance between the point and intersected road points 
        dist = []
        for j in range(0, len(r_in)):
            d = new_distance(x, y, rx[j], ry[j])
            dist.append(d)  
        #print("Distance list's length",len(dist))
            
        rid = r_in.loc[:,'RDID']
        #Create DF
        df_rd = pd.DataFrame({'RDID': rid, 'Dist':dist}).sort_values(by='Dist')
        #print(df_rd.head(1))
        #print(df_rd.iloc[0, 0])
        #r_id.append(df_rd.iloc[0, 0])
        return df_rd.iloc[0, 0]

In [11]:
def go(data):
    data['RID'] = data.apply(assign_rid, args=(road,),axis=1)
    return data
    
def parallelize(data, func):
    #Cores
    num_cores = multiprocessing.cpu_count()-1
    num_partitions = num_cores
    #Split
    data_split = np.array_split(data, num_partitions)
    #Pools
    pool = multiprocessing.Pool(num_cores)
    
    df = pd.concat(pool.map(func, data_split))
    return df

    pool.close()
    pool.join()

### Assign Function Test

In [12]:
test = homect.iloc[:10,:].copy()
#test['SrdID'] = np.repeat(0,len(test))

In [13]:
test

              hhold       long        lat                    geometry
0     09001010101h0 -73.698597  41.112328  POINT (-73.69860 41.11233)
1     09001010101h1 -73.670429  41.097875  POINT (-73.67043 41.09788)
2    09001010101h10 -73.667156  41.046854  POINT (-73.66716 41.04685)
3   09001010101h100 -73.720042  41.099381  POINT (-73.72004 41.09938)
4  09001010101h1000 -73.684385  41.056047  POINT (-73.68439 41.05605)
5  09001010101h1001 -73.688061  41.090949  POINT (-73.68806 41.09095)
6  09001010101h1002 -73.684679  41.055643  POINT (-73.68468 41.05564)
7  09001010101h1003 -73.689619  41.056749  POINT (-73.68962 41.05675)
8  09001010101h1004 -73.659922  41.048102  POINT (-73.65992 41.04810)
9  09001010101h1005 -73.667787  41.037095  POINT (-73.66779 41.03709)

In [14]:
test['RID'] = test.apply(assign_rid, args=(road,),axis=1)

In [16]:
test

              hhold       long        lat                    geometry     RID
0     09001010101h0 -73.698597  41.112328  POINT (-73.69860 41.11233)  225136
1     09001010101h1 -73.670429  41.097875  POINT (-73.67043 41.09788)    4084
2    09001010101h10 -73.667156  41.046854  POINT (-73.66716 41.04685)  129288
3   09001010101h100 -73.720042  41.099381  POINT (-73.72004 41.09938)  132056
4  09001010101h1000 -73.684385  41.056047  POINT (-73.68439 41.05605)  236212
5  09001010101h1001 -73.688061  41.090949  POINT (-73.68806 41.09095)  557005
6  09001010101h1002 -73.684679  41.055643  POINT (-73.68468 41.05564)  236212
7  09001010101h1003 -73.689619  41.056749  POINT (-73.68962 41.05675)    3275
8  09001010101h1004 -73.659922  41.048102  POINT (-73.65992 41.04810)  236166
9  09001010101h1005 -73.667787  41.037095  POINT (-73.66779 41.03709)  558618

In [17]:
test.merge(road, on='RID', how='inner')

,hhold,long,lat,geometry_x,RID,RDID,STATE,Long,Lat,geometry_y
0,09001010101h0,-73.698597,41.112328,POINT (-73.69860 41.11233),225136,225136,09,-73.697749,41.113425,POINT (-73.69775 41.11342)
1,09001010101h1,-73.670429,41.097875,POINT (-73.67043 41.09788),4084,4084,09,-73.670365,41.097601,POINT (-73.67037 41.09760)
2,09001010101h10,-73.667156,41.046854,POINT (-73.66716 41.04685),129288,129288,09,-73.667526,41.047768,POINT (-73.66753 41.04777)
3,09001010101h100,-73.720042,41.099381,POINT (-73.72004 41.09938),132056,132056,09,-73.720185,41.099778,POINT (-73.72019 41.09978)
4,09001010101h1000,-73.684385,41.056047,POINT (-73.68439 41.05605),236212,236212,09,-73.684882,41.055706,POINT (-73.68488 41.05571)
5,09001010101h1002,-73.684679,41.055643,POINT (-73.68468 41.05564),236212,236212,09,-73.684882,41.055706,POINT (-73.68488 41.05571)
6,09001010101h1001,-73.688061,41.090949,POINT (-73.68806 41.09095),557005,557005,09,-73.687929,41.090138,POINT (-73.68793 41.09014)
7,09001010101h1003,-73.689619,41.056749,POINT (-73.68962 41.05675),3275,3275,09,-73.690297,41.056475,POINT (-73.69030 41.05648)
8,09001010101h1004,-73.659922,41.048102,POINT (-73.65992 41.04810),236166,236166,09,-73.660382,41.047974,POINT (-73.66038 41.04797)
9,09001010101h1005,-73.667787,41.037095,POINT (-73.66779 41.03709),558618,558618,09,-73.667687,41.037297,POINT (-73.66769 41.03730)

### Parallelize Test

In [18]:
test = homect.iloc[:50,:].copy()
#test['SrdID'] = np.repeat(0,len(test))

In [19]:
#Test 
start_time = timeit.default_timer()
test_p = parallelize(test, go)
elapsed = timeit.default_timer() - start_time
print(elapsed)

132.45157498899994

In [20]:
test_p

,hhold,long,lat,geometry,RID
0,09001010101h0,-73.698597,41.112328,POINT (-73.69860 41.11233),225136
1,09001010101h1,-73.670429,41.097875,POINT (-73.67043 41.09788),4084
2,09001010101h10,-73.667156,41.046854,POINT (-73.66716 41.04685),129288
3,09001010101h100,-73.720042,41.099381,POINT (-73.72004 41.09938),132056
4,09001010101h1000,-73.684385,41.056047,POINT (-73.68439 41.05605),236212
5,09001010101h1001,-73.688061,41.090949,POINT (-73.68806 41.09095),557005
6,09001010101h1002,-73.684679,41.055643,POINT (-73.68468 41.05564),236212
7,09001010101h1003,-73.689619,41.056749,POINT (-73.68962 41.05675),3275
8,09001010101h1004,-73.659922,41.048102,POINT (-73.65992 41.04810),236166
9,09001010101h1005,-73.667787,41.037095,POINT (-73.66779 41.03709),558618
10,09001010101h1006,-73.674583,41.104145,POINT (-73.67458 41.10415),819
11,09001010101h1007,-73.677236,41.092867,POINT (-73.67724 41.09287),132955
12,09001010101h1008,-73.679458,41.041589,POINT (-73.67946 41.04159),1041606
13,09001010101h1009,-73.667658,41.084177,POINT (-73.66766 41.08418),232570
14,09001010101h101,-73.653010,41.066441,POINT (-73.65301 41.06644),236163
15,09001010101h1010,-73.713601,41.089726,POINT (-73.71360 41.08973),745
16,09001010101h1011,-73.698672,41.110491,POINT (-73.69867 41.11049),1492
17,09001010101h1012,-73.691829,41.080176,POINT (-73.69183 41.08018),135704
18,09001010101h1013,-73.688371,41.058847,POINT (-73.68837 41.05885),136632
19,09001010101h1014,-73.705120,41.090081,POINT (-73.70512 41.09008),134127
20,09001010101h1015,-73.675960,41.091089,POINT (-73.67596 41.09109),4725
21,09001010101h1016,-73.701452,41.095792,POINT (-73.70145 41.09579),237970
22,09001010101h1017,-73.675136,41.109972,POINT (-73.67514 41.10997),227907
23,09001010101h1018,-73.673584,41.063882,POINT (-73.67358 41.06388),1489
24,09001010101h1019,-73.686726,41.097422,POINT (-73.68673 41.09742),230636
25,09001010101h102,-73.683080,41.110966,POINT (-73.68308 41.11097),238374
26,09001010101h1020,-73.663116,41.078336,POINT (-73.66312 41.07834),221879
27,09001010101h1021,-73.685893,41.119591,POINT (-73.68589 41.11959),227436
28,09001010101h1022,-73.693200,41.100576,POINT (-73.69320 41.10058),137569
29,09001010101h1023,-73.695695,41.070420,POINT (-73.69569 41.07042),6835
30,09001010101h1024,-73.721253,41.099980,POINT (-73.72125 41.09998),129970
31,09001010101h1025,-73.663861,41.051031,POINT (-73.66386 41.05103),130678
32,09001010101h1026,-73.690082,41.069107,POINT (-73.69008 41.06911),230208
33,09001010101h1027,-73.659469,41.068738,POINT (-73.65947 41.06874),131853
34,09001010101h1028,-73.695931,41.115155,POINT (-73.69593 41.11516),558975
35,09001010101h1029,-73.676104,41.111330,POINT (-73.67610 41.11133),235855
36,09001010101h103,-73.674201,41.109355,POINT (-73.67420 41.10935),135515
37,09001010101h1030,-73.694952,41.061103,POINT (-73.69495 41.06110),222594
38,09001010101h1031,-73.668055,41.112518,POINT (-73.66805 41.11252),129480
39,09001010101h1032,-73.690761,41.066499,POINT (-73.69076 41.06650),134545
40,09001010101h1033,-73.676270,41.067606,POINT (-73.67627 41.06761),225352
41,09001010101h1034,-73.669356,41.091129,POINT (-73.66936 41.09113),129478
42,09001010101h1035,-73.704240,41.084641,POINT (-73.70424 41.08464),135291
43,09001010101h1036,-73.678674,41.054213,POINT (-73.67867 41.05421),227908
44,09001010101h1037,-73.724490,41.098850,POINT (-73.72449 41.09885),1699
45,09001010101h1038,-73.710478,41.091113,POINT (-73.71048 41.09111),5617
46,09001010101h1039,-73.658565,41.071635,POINT (-73.65856 41.07164),233029
47,09001010101h104,-73.671599,41.098282,POINT (-73.67160 41.09828),2379
48,09001010101h1040,-73.694325,41.065565,POINT (-73.69432 41.06556),2504
49,09001010101h1041,-73.672763,41.098348,POINT (-73.67276 41.09835),6850

In [21]:
test_p.merge(road, on='RID', how='inner')

,hhold,long,lat,geometry_x,RID,RDID,STATE,Long,Lat,geometry_y
0,09001010101h0,-73.698597,41.112328,POINT (-73.69860 41.11233),225136,225136,09,-73.697749,41.113425,POINT (-73.69775 41.11342)
1,09001010101h1,-73.670429,41.097875,POINT (-73.67043 41.09788),4084,4084,09,-73.670365,41.097601,POINT (-73.67037 41.09760)
2,09001010101h10,-73.667156,41.046854,POINT (-73.66716 41.04685),129288,129288,09,-73.667526,41.047768,POINT (-73.66753 41.04777)
3,09001010101h100,-73.720042,41.099381,POINT (-73.72004 41.09938),132056,132056,09,-73.720185,41.099778,POINT (-73.72019 41.09978)
4,09001010101h1000,-73.684385,41.056047,POINT (-73.68439 41.05605),236212,236212,09,-73.684882,41.055706,POINT (-73.68488 41.05571)
5,09001010101h1002,-73.684679,41.055643,POINT (-73.68468 41.05564),236212,236212,09,-73.684882,41.055706,POINT (-73.68488 41.05571)
6,09001010101h1001,-73.688061,41.090949,POINT (-73.68806 41.09095),557005,557005,09,-73.687929,41.090138,POINT (-73.68793 41.09014)
7,09001010101h1003,-73.689619,41.056749,POINT (-73.68962 41.05675),3275,3275,09,-73.690297,41.056475,POINT (-73.69030 41.05648)
8,09001010101h1004,-73.659922,41.048102,POINT (-73.65992 41.04810),236166,236166,09,-73.660382,41.047974,POINT (-73.66038 41.04797)
9,09001010101h1005,-73.667787,41.037095,POINT (-73.66779 41.03709),558618,558618,09,-73.667687,41.037297,POINT (-73.66769 41.03730)
10,09001010101h1006,-73.674583,41.104145,POINT (-73.67458 41.10415),819,819,09,-73.673956,41.104149,POINT (-73.67396 41.10415)
11,09001010101h1007,-73.677236,41.092867,POINT (-73.67724 41.09287),132955,132955,09,-73.677162,41.092425,POINT (-73.67716 41.09242)
12,09001010101h1008,-73.679458,41.041589,POINT (-73.67946 41.04159),1041606,1041606,09,-73.679123,41.041165,POINT (-73.67912 41.04116)
13,09001010101h1009,-73.667658,41.084177,POINT (-73.66766 41.08418),232570,232570,09,-73.667156,41.084672,POINT (-73.66716 41.08467)
14,09001010101h101,-73.653010,41.066441,POINT (-73.65301 41.06644),236163,236163,09,-73.653171,41.066569,POINT (-73.65317 41.06657)
15,09001010101h1010,-73.713601,41.089726,POINT (-73.71360 41.08973),745,745,09,-73.713459,41.089427,POINT (-73.71346 41.08943)
16,09001010101h1011,-73.698672,41.110491,POINT (-73.69867 41.11049),1492,1492,09,-73.698529,41.110228,POINT (-73.69853 41.11023)
17,09001010101h1012,-73.691829,41.080176,POINT (-73.69183 41.08018),135704,135704,09,-73.691842,41.080082,POINT (-73.69184 41.08008)
18,09001010101h1013,-73.688371,41.058847,POINT (-73.68837 41.05885),136632,136632,09,-73.688311,41.058567,POINT (-73.68831 41.05857)
19,09001010101h1014,-73.705120,41.090081,POINT (-73.70512 41.09008),134127,134127,09,-73.704511,41.089492,POINT (-73.70451 41.08949)
20,09001010101h1015,-73.675960,41.091089,POINT (-73.67596 41.09109),4725,4725,09,-73.676899,41.091414,POINT (-73.67690 41.09141)
21,09001010101h1016,-73.701452,41.095792,POINT (-73.70145 41.09579),237970,237970,09,-73.701268,41.095813,POINT (-73.70127 41.09581)
22,09001010101h1017,-73.675136,41.109972,POINT (-73.67514 41.10997),227907,227907,09,-73.674872,41.110023,POINT (-73.67487 41.11002)
23,09001010101h1018,-73.673584,41.063882,POINT (-73.67358 41.06388),1489,1489,09,-73.673737,41.063883,POINT (-73.67374 41.06388)
24,09001010101h1019,-73.686726,41.097422,POINT (-73.68673 41.09742),230636,230636,09,-73.687853,41.096503,POINT (-73.68785 41.09650)
25,09001010101h102,-73.683080,41.110966,POINT (-73.68308 41.11097),238374,238374,09,-73.683071,41.111700,POINT (-73.68307 41.11170)
26,09001010101h1020,-73.663116,41.078336,POINT (-73.66312 41.07834),221879,221879,09,-73.663413,41.078284,POINT (-73.66341 41.07828)
27,09001010101h1021,-73.685893,41.119591,POINT (-73.68589 41.11959),227436,227436,09,-73.685789,41.119335,POINT (-73.68579 41.11934)
28,09001010101h1022,-73.693200,41.100576,POINT (-73.69320 41.10058),137569,137569,09,-73.693959,41.100176,POINT (-73.69396 41.10018)
29,09001010101h1023,-73.695695,41.070420,POINT (-73.69569 41.07042),6835,6835,09,-73.695794,41.070426,POINT (-73.69579 41.07043)
30,09001010101h1024,-73.721253,41.099980,POINT (-73.72125 41.09998),129970,129970,09,-73.722201,41.099759,POINT (-73.72220 41.09976)
31,09001010101h1025,-73.663861,41.051031,POINT (-73.66386 41.05103),130678,130678,09,-73.663637,41.050941,POINT (-73.66364 41.05094)
32,09001010101h1026,-73.690082,41.069107,POINT (-73.69008 41.06911),230208,230208,09,-73.693196,41.068316,POINT (-73.69320 41.06832)
33,09001010101h1027,-73.659469,41.068738,POINT (-73.65947 41.06874),131853,131853,09,-73.659332,41.069454,POINT (-73.65933 41.06945)
34,09001010101h1028,-73.695931,41.115155,POINT (-73.69593 41.11516),558975,558975,09,-73.695867,41.114996,POINT (-73.69587 41.11500)
35,09001010101h1029,-73.676104,41.111330,POINT (-73.67610 41.11133),235855,235855,09,-73.675512,41.110941,POINT (-73.67551 41.11094)
36,09001010101h103,-73.674201,41.109355,POINT (-73.67420 41.10935),135515,135515,09,-73.674136,41.109232,POINT (-73.67414 41.10923)
37,09001010101h1030,-73.694952,41.061103,POINT (-73.69495 41.06110),222594,222594,09,-73.694745,41.060496,POINT (-73.69474 41.06050)
38,09001010101h1031,-73.668055,41.112518,POINT (-73.66805 41.11252),129480,129480,09,-73.668449,41.112394,POINT (-73.66845 41.11239)
39,09001010101h1032,-73.690761,41.066499,POINT (-73.69076 41.06650),134545,134545,09,-73.691451,41.065471,POINT (-73.69145 41.06547)
40,09001010101h1033,-73.676270,41.067606,POINT (-73.67627 41.06761),225352,225352,09,-73.676402,41.067608,POINT (-73.67640 41.06761)
41,09001010101h1034,-73.669356,41.091129,POINT (-73.66936 41.09113),129478,129478,09,-73.669458,41.090619,POINT (-73.66946 41.09062)
42,09001010101h1035,-73.704240,41.084641,POINT (-73.70424 41.08464),135291,135291,09,-73.705488,41.085607,POINT (-73.70549 41.08561)
43,09001010101h1036,-73.678674,41.054213,POINT (-73.67867 41.05421),227908,227908,09,-73.678876,41.054259,POINT (-73.67888 41.05426)
44,09001010101h1037,-73.724490,41.098850,POINT (-73.72449 41.09885),1699,1699,09,-73.724185,41.098894,POINT (-73.72418 41.09889)
45,09001010101h1038,-73.710478,41.091113,POINT (-73.71048 41.09111),5617,5617,09,-73.709698,41.091396,POINT (-73.70970 41.09140)
46,09001010101h1039,-73.658565,41.071635,POINT (-73.65856 41.07164),233029,233029,09,-73.658301,41.071684,POINT (-73.65830 41.07168)
47,09001010101h104,-73.671599,41.098282,POINT (-73.67160 41.09828),2379,2379,09,-73.671682,41.098297,POINT (-73.67168 41.09830)
48,09001010101h1040,-73.694325,41.065565,POINT (-73.69432 41.06556),2504,2504,09,-73.695112,41.066415,POINT (-73.69511 41.06642)
49,09001010101h1041,-73.672763,41.098348,POINT (-73.67276 41.09835),6850,6850,09,-73.672770,41.099024,POINT (-73.67277 41.09902)

### Apply Full Function

In [ ]:
#Apply 
if __name__=='__main__':
    print('Start running...')
    #set timer
    start_time = timeit.default_timer()
    #apply
    #wrk_r = parallelize(wrk, go)
    #pa_r = parallelize(homepa, go)
    ct_r = parallelize(homect, go)
    
    elapsed = timeit.default_timer() - start_time
    print("Total Time(s):", elapsed)
    print('End program')

Start running...

In [27]:
ct_r.head()

              hhold       long        lat                    geometry     RID
0     42017100406h0 -74.855637  40.167156  POINT (-74.85564 40.16716)  740321
1     42017100406h1 -74.846031  40.173643  POINT (-74.84603 40.17364)  547316
2    42017100406h10 -74.844242  40.168111  POINT (-74.84424 40.16811)  127096
3   42017100406h100 -74.846836  40.167468  POINT (-74.84684 40.16747)  548459
4  42017100406h1000 -74.854315  40.155588  POINT (-74.85432 40.15559)  550623

In [30]:
ct_r.iloc[:,[0,-1]].to_csv('home_ct_rid_oct.csv')